"""crear tabla tecnicos y tecnico_empresa

Revision ID: 071d513d05ea
Revises: 41b1f4ec23f1
Create Date: 2026-04-18 17:20:17.210818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071d513d05ea'
down_revision: Union[str, Sequence[str], None] = '41b1f4ec23f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tecnicos_id'), 'tecnicos', ['id'], unique=False)
    op.create_table('tecnico_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tecnico_empresa_id'), 'tecnico_empresa', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tecnico_empresa_id'), table_name='tecnico_empresa')
    op.drop_table('tecnico_empresa')
    op.drop_index(op.f('ix_tecnicos_id'), table_name='tecnicos')
    op.drop_table('tecnicos')
    # ### end Alembic commands ###
